### ISSUE TITLE
js error with moodle upgrade

### ISSUE THREAD

**Issue by jamesalvarez** [h5p/moodle-mod_hvp#356]
Hello, since I upgrade my moodle site to 3.9 I have been getting js errors with h5p activites with branching scenarios only.

Chrome console:

Uncaught TypeError: e.video.play is not a function
at i.attach (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:26163)
at Object.H5P.newRunnable (h5p.js?ver=2020020500:954)
at LibraryScreen.appendRunnable (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27599)
at LibraryScreen.createLibraryElement (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27553)
at new LibraryScreen (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:27295)
at H5P.BranchingScenario.self.attach (8b20f34f2a466dd1fae752c21ad512eb61846d97.js:26952)
at Object.H5P.newRunnable (h5p.js?ver=2020020500:954)
at HTMLDivElement. (h5p.js?ver=2020020500:137)
at Function.each (jquery.js?ver=2020020500:2)
at init.each (jquery.js?ver=2020020500:2)

Do you know if this is likely something to do with moodle or this h5p plugin? Have fully upgrade h5p and all plugins.

**Comment by thomasmars** [comment]
Were you able to resolve this ?
What are you trying to do when this happens ?
Can you provide detailed steps to reproduce this or provide a link to where the error can be seen ?
Also include any php errors if there are any.

**Comment by jamesalvarez** [comment]
Hi Thomas - we moved away from using the Branching scenarios as a result, if you are keen to get the error, I can take a look and see if I can reproduce it on our site.

**Comment by thomasmars** [comment]
Yes, please let me know if you are able to reproduce and the steps necessary, and also attach the .h5p this happens with.

**Comment by jamesalvarez** [comment]
Well now everything appears to be working!  The issue was when we had videos in the branches (so I'm told) but now it appears to just be working including with the videos now- so am happy to close.
